[profile.default]
src = 'src'
test = 'src/test'
test_match = '*.t.sol'
no_match_path = 'src/LibTest.sol'
allow_paths = ['../']
evm_version = 'cancun'
auto_detect_solc = true
optimizer = true
via_ir = true

[lint]
lint_on_build = false